export const COUNTRY_LANGUAGES: Record<string, string[]> = {
  PK: ['Urdu', 'English'],
  SA: ['Arabic'],
  AE: ['Arabic', 'English'],
  QA: ['Arabic'],
  KW: ['Arabic'],
  BH: ['Arabic'],
  OM: ['Arabic'],
  EG: ['Arabic'],
  GB: ['English'],
  US: ['English'],
  CA: ['English', 'French'],
  AU: ['English'],
  TR: ['Turkish'],
  MY: ['Malay', 'English'],
  ID: ['Indonesian'],
  BD: ['Bengali'],
  IN: ['Hindi', 'Urdu', 'English'],
  IR: ['Persian'],
  AF: ['Pashto', 'Persian'],
  FR: ['French'],
  DE: ['German'],
  ES: ['Spanish'],
  IT: ['Italian'],
  NL: ['Dutch'],
  SE: ['Swedish'],
  NO: ['Norwegian'],
  DK: ['Danish'],
  ZA: ['English'],
  NG: ['Hausa', 'English'],
  SO: ['Somali', 'Arabic'],
  KE: ['Swahili', 'English'],
  TZ: ['Swahili'],
  MA: ['Arabic', 'French'],
  DZ: ['Arabic', 'French'],
  TN: ['Arabic', 'French'],
  LY: ['Arabic'],
  SD: ['Arabic'],
  SY: ['Arabic'],
  IQ: ['Arabic', 'Kurdish'],
  JO: ['Arabic'],
  LB: ['Arabic', 'French'],
  PS: ['Arabic'],
  YE: ['Arabic'],
  UZ: ['Uzbek', 'Russian'],
  KZ: ['Kazakh', 'Russian'],
  TJ: ['Tajik'],
  RU: ['Russian'],
  CN: ['Chinese'],
  JP: ['Japanese'],
  KR: ['Korean'],
  BR: ['Portuguese'],
  MX: ['Spanish'],
};

export const PREDEFINED_LANGUAGES: string[] = [
  'English',
  'Arabic',
  'Urdu',
  'Pashto',
  'Punjabi',
  'Sindhi',
  'Balochi',
  'Turkish',
  'French',
  'Malay',
  'Indonesian',
  'Bengali',
  'Hindi',
  'Persian',
  'Swahili',
  'Somali',
  'Hausa',
  'Tamil',
  'Spanish',
  'German',
  'Russian',
  'Chinese',
  'Dutch',
];

/**
 * Returns primary languages associated with an ISO country code.
 */
export function getLanguagesForCountry(countryCode?: string): string[] {
  if (!countryCode) return [];
  const normalized = countryCode.toUpperCase().trim();
  return COUNTRY_LANGUAGES[normalized] || ['English'];
}
