import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { DatabaseAdminController } from './database-admin.controller';
import { DatabaseAdminService } from './database-admin.service';
import { AuditLogsModule } from '../audit-logs/audit-logs.module';
import { RedisCacheModule } from '../cache/redis-cache.module';
import {
  User, UserSchema,
  Teacher, TeacherSchema,
  Student, StudentSchema,
  Course, CourseSchema,
  Enrollment, EnrollmentSchema,
  ClassSession, ClassSessionSchema,
  WeeklyScheduleSlot, WeeklyScheduleSlotSchema,
  Attendance, AttendanceSchema,
  Recording, RecordingSchema,
  TranscriptSegment, TranscriptSegmentSchema,
  ClassReview, ClassReviewSchema,
  AIReport, AIReportSchema,
  RescheduleRequest, RescheduleRequestSchema,
  SupervisorAssignment, SupervisorAssignmentSchema,
  ReviewerAssignment, ReviewerAssignmentSchema,
  StudentFeedback, StudentFeedbackSchema,
  FeeStructure, FeeStructureSchema,
  Invoice, InvoiceSchema,
  Expense, ExpenseSchema,
  Income, IncomeSchema,
  SalaryPayment, SalaryPaymentSchema,
  SalarySlip, SalarySlipSchema,
  SalaryConfig, SalaryConfigSchema,
  LeaveRequest, LeaveRequestSchema,
  LeaveBalance, LeaveBalanceSchema,
  Ticket, TicketSchema,
  TicketComment, TicketCommentSchema,
  Notification, NotificationSchema,
  Material, MaterialSchema,
  SubjectCategory, SubjectCategorySchema,
  AuditLog, AuditLogSchema,
  PipelineLog, PipelineLogSchema,
  Counter, CounterSchema,
  Permission, PermissionSchema,
  RolePermission, RolePermissionSchema,
  SystemSetting, SystemSettingSchema,
} from '../schemas';

@Module({
  imports: [
    MongooseModule.forFeature([
      { name: User.name, schema: UserSchema },
      { name: Teacher.name, schema: TeacherSchema },
      { name: Student.name, schema: StudentSchema },
      { name: Course.name, schema: CourseSchema },
      { name: Enrollment.name, schema: EnrollmentSchema },
      { name: ClassSession.name, schema: ClassSessionSchema },
      { name: WeeklyScheduleSlot.name, schema: WeeklyScheduleSlotSchema },
      { name: Attendance.name, schema: AttendanceSchema },
      { name: Recording.name, schema: RecordingSchema },
      { name: TranscriptSegment.name, schema: TranscriptSegmentSchema },
      { name: ClassReview.name, schema: ClassReviewSchema },
      { name: AIReport.name, schema: AIReportSchema },
      { name: RescheduleRequest.name, schema: RescheduleRequestSchema },
      { name: SupervisorAssignment.name, schema: SupervisorAssignmentSchema },
      { name: ReviewerAssignment.name, schema: ReviewerAssignmentSchema },
      { name: StudentFeedback.name, schema: StudentFeedbackSchema },
      { name: FeeStructure.name, schema: FeeStructureSchema },
      { name: Invoice.name, schema: InvoiceSchema },
      { name: Expense.name, schema: ExpenseSchema },
      { name: Income.name, schema: IncomeSchema },
      { name: SalaryPayment.name, schema: SalaryPaymentSchema },
      { name: SalarySlip.name, schema: SalarySlipSchema },
      { name: SalaryConfig.name, schema: SalaryConfigSchema },
      { name: LeaveRequest.name, schema: LeaveRequestSchema },
      { name: LeaveBalance.name, schema: LeaveBalanceSchema },
      { name: Ticket.name, schema: TicketSchema },
      { name: TicketComment.name, schema: TicketCommentSchema },
      { name: Notification.name, schema: NotificationSchema },
      { name: Material.name, schema: MaterialSchema },
      { name: SubjectCategory.name, schema: SubjectCategorySchema },
      { name: AuditLog.name, schema: AuditLogSchema },
      { name: PipelineLog.name, schema: PipelineLogSchema },
      { name: Counter.name, schema: CounterSchema },
      { name: Permission.name, schema: PermissionSchema },
      { name: RolePermission.name, schema: RolePermissionSchema },
      { name: SystemSetting.name, schema: SystemSettingSchema },
    ]),
    AuditLogsModule,
    RedisCacheModule,
  ],
  controllers: [DatabaseAdminController],
  providers: [DatabaseAdminService],
  exports: [DatabaseAdminService],
})
export class DatabaseAdminModule {}
